### ISSUE TITLE
Problem with sorting: private method `visit_Ransack_Nodes_Sort' called for #<Ransack::Visitor>

### ISSUE THREAD

**Issue by Gee-Bee** [shioyama/mobility-ransack#15] opened 2021-01-27 13:01 UTC
There is an error thrown 
```text
private method `visit_Ransack_Nodes_Sort' called for #<Ransack::Visitor>
```
when sorting is added to ransack params.

For example these:
```ruby
Post.ransack(title_cont: "foo", s: "title").result
Post.ransack(title_cont: "foo", s: "created_at").result
```
are throwing the error, while calling without sorting parameter
```ruby
Post.ransack(title_cont: "foo").result
```
is working correctly.

`visit_Ransack_Nodes_Sort` is indeed private method in `Ransack::Visitor`.
```ruby
irb(main):018:0> Ransack::Visitor.private_instance_methods.include?(:visit_Ransack_Nodes_Sort)
=> true
```
It's called [here](https://github.com/shioyama/mobility-ransack/blob/ce9034164ce27e1b2029434c03887cb25415bb55/lib/mobility/plugins/ransack.rb#L34)

**Comment by shioyama** [comment] 2021-06-25 22:48
I can change that code to use `send`, but I don't see what you're seeing. Here's the method:

https://github.com/activerecord-hackery/ransack/blob/63990fc9ee344bb1caa938185b564b258d50ee50/lib/ransack/adapters/active_record/ransack/visitor.rb#L23-L34

it doesn't seem to be private.

And indeed with Ransack 2.4.2 (which AFAICT is the latest):

```ruby
Ransack::Visitor.private_instance_methods.include?(:visit_Ransack_Nodes_Sort)
#=> false
```

Which version of Ransack are you using? And do you have anything else that might be patching that method?

**Comment by shioyama** [comment] 2021-06-25 22:49
I'm closing this one since I can't reproduce. Feel free to re-open if you have code to reproduce or a failing test.

**Closed as completed by shioyama** 2021-06-25 22:49 UTC
Labels: bug

**Comment by Gee-Bee** [comment] 2021-09-07 09:22
> And do you have anything else that might be patching that method?

You're right @shioyama. Looks like `jsonapi.rb` gem changed method visibility.
I filed an issue in the appropriate repo: https://github.com/stas/jsonapi.rb/issues/66
